-- Databricks notebook source
-- MAGIC %md
-- MAGIC ### Example Exploratory Notebook
-- MAGIC
-- MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
-- MAGIC
-- MAGIC **Note**: This notebook is not executed as part of the pipeline.

-- COMMAND ----------

-- MAGIC %python
-- MAGIC import sys
-- MAGIC
-- MAGIC sys.path.append("/Workspace/Users/alex.feng@databricks.com/campaign_conversion")

-- COMMAND ----------

-- !!! Before performing any data analysis, make sure to run the pipeline to materialize the sample datasets. The tables referenced in this notebook depend on that step.

USE CATALOG `workspace`;
USE SCHEMA `marketing_workshop`;

SELECT * from `raw_campaigns`;

-- COMMAND ----------

select count(distinct Cost) from raw_campaigns

-- COMMAND ----------

select * from workspace.marketing_workshop.raw_events limit 10;

-- COMMAND ----------

select EventType, count(EventType) from workspace.marketing_workshop.raw_events group by EventType;

-- COMMAND ----------


