CREATE OR REFRESH STREAMING TABLE silver_campaigns(
  CONSTRAINT valid_campaign_id EXPECT (CampaignId IS NOT NULL) ON VIOLATION DROP ROW,
  CONSTRAINT valid_campaign_name EXPECT (CampaignName IS NOT NULL) ON VIOLATION DROP ROW,
  CONSTRAINT valid_campaign_description EXPECT (CampaignDescription IS NOT NULL) ON VIOLATION DROP ROW,
  CONSTRAINT valid_subject_line EXPECT (SubjectLine IS NOT NULL) ON VIOLATION DROP ROW,
  CONSTRAINT valid_template EXPECT (Template IS NOT NULL) ON VIOLATION DROP ROW,
  CONSTRAINT valid_cost EXPECT (Cost IS NOT NULL) ON VIOLATION DROP ROW,
  CONSTRAINT valid_start_date EXPECT (StartDate IS NOT NULL) ON VIOLATION DROP ROW,
  CONSTRAINT valid_end_date EXPECT (EndDate IS NOT NULL) ON VIOLATION DROP ROW,
  CONSTRAINT valid_mailing_list EXPECT (MailingList IS NOT NULL) ON VIOLATION DROP ROW
) AS SELECT * FROM stream(raw_campaigns);


CREATE OR REFRESH STREAMING TABLE silver_events(
  CONSTRAINT valid_event_id EXPECT (EventId IS NOT NULL) ON VIOLATION DROP ROW,
  CONSTRAINT valid_campaign_id EXPECT (CampaignId IS NOT NULL) ON VIOLATION DROP ROW,
  CONSTRAINT valid_contact_id EXPECT (ContactId IS NOT NULL) ON VIOLATION DROP ROW,
  CONSTRAINT valid_event_type EXPECT (EventType IS NOT NULL) ON VIOLATION DROP ROW,
  CONSTRAINT valid_event_date EXPECT (EventDate IS NOT NULL) ON VIOLATION DROP ROW,
  CONSTRAINT valid_metadata EXPECT (Metadata IS NOT NULL) ON VIOLATION DROP ROW
) AS SELECT * FROM stream(raw_events);

-- CREATE OR REFRESH STREAMING TABLE silver_feedback
